export const env = `PUBLIC_CLERK_PUBLISHABLE_KEY=
PUBLIC_CLERK_SIGN_IN_URL=/login
PUBLIC_CLERK_SIGN_UP_URL=/signup
PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=/dashboard
PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=/dashboard

CLERK_SECRET_KEY=
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/app`;
